### ISSUE TITLE
Unable to pull singularity image? 

### ISSUE THREAD

**Issue by forty2wallabyway** [epi2me-labs/wf-flu#10]
### Operating System

Ubuntu 22.04

### Workflow Version

24.04.3

### Workflow Execution

Command line (Cluster)

### CLI command run

nextflow run epi2me-labs/wf-flu \
--downsample 50 \
--fastq 'wf-flu-demo/fastq' \
--sample_sheet 'wf-flu-demo/sample_sheet.csv' \
-profile singularity

### Workflow Execution - CLI Execution Profile

singularity

### What happened?

Command error:
  FATAL:   container creation failed: mount /proc/self/fd/4->/usr/local/var/singularity/mnt/session/rootfs error: while mounting image /proc/self/fd/4: kernel reported a bad superblock for squashfs image partition, possible causes are that your kernel doesn't support the compression algorithm or the image is corrupted

### Relevant log output

```shell
ERROR ~ Error executing process > 'pipeline:getVersions'

Caused by:
  Process `pipeline:getVersions` terminated with an error exit status (255)


Command executed:

  python -c "import pysam; print(f'pysam,{pysam.__version__}')" >> versions.txt
  fastcat --version | sed 's/^/fastcat,/' >> versions.txt
  bcftools --version | head -1 | sed 's/ /,/' >> versions.txt
  samtools --version | grep samtools | head -1 | sed 's/ /,/' >> versions.txt

Command exit status:
  255

Command output:
  (empty)

Command error:
  FATAL:   container creation failed: mount /proc/self/fd/4->/usr/local/var/singularity/mnt/session/rootfs error: while mounting image /proc/self/fd/4: kernel reported a bad superblock for squashfs image partition, possible causes are that your kernel doesn't support the compression algorithm or the image is corrupted
```

### Were you able to successfully run the latest version of the workflow with the demo data?

no

**Comment by nrhorner** [comment]
Hi @forty2wallabyway This might be related to a singularity bug that was fixed in v3.5.1. 
https://github.com/apptainer/singularity/issues/5466

 Which version are you using?

**Comment by forty2wallabyway** [comment]
Thanks @nrhorner I was using v3.5.0 and updating to a newer version solved my issue!

**Comment by forty2wallabyway** [comment]
Thanks @nrhorner I was using v3.5.0 and updating to a newer version solved my issue!
