### ISSUE TITLE
Sample sheet

### ISSUE THREAD

**Issue by FDufrasne** [epi2me-labs/wf-flu#2]
### What happened?

Dear,

It appears that providing sample sheet is now mandatory in the upgraded epi2me-labs/wf-flu v0.0.8.
It is sometimes useful to prepare and upload this sample sheet but it is not always the case.
Would it possible to let it as an option rather than an obligation ? Currently, if no sample sheet is provided, it's impossible to launch the workflow.

Many thanks,

François

### Operating System

ubuntu 20.04

### Workflow Execution

EPI2ME Labs desktop application

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

version 22.04.5

### Relevant log output

```shell
NA
```

**Comment by mattdmem** [comment]
Thanks for this @FDufrasne - there are no current plans to make sample sheet optional. Is there a use case where you cannot create one?

**Comment by mattdmem** [comment]
Sample sheet is now optional in v0.0.9!

**Comment by FDufrasne** [comment]
Dear,

Nice ! Many thanks !

François
