### ISSUE TITLE
[Question]: How to use version v0.0.9

### ISSUE THREAD

**Issue by gilmansiugroup** [epi2me-labs/wf-flu#3]
### What happened?

Hi! We would like to try the latest revision `v0.0.9`, but when we tried, it returns the following error message. May we know how to handle this issue? Thank you very much!

> nextflow run epi2me-labs/wf-flu -r v0.0.9 --help
> N E X T F L O W  ~  version 21.10.4
> Cannot find revision `v0.0.9` -- Make sure that it exists in the remote repository `https://github.com/epi2me-labs/wf-flu`
> 

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

Docker

### Workflow Version

v0.0.9

### Relevant log output

```shell
nextflow run epi2me-labs/wf-flu -r v0.0.9 --help
N E X T F L O W  ~  version 21.10.4
Cannot find revision `v0.0.9` -- Make sure that it exists in the remote repository `https://github.com/epi2me-labs/wf-flu`
```

**Comment by llk578496** [comment]
We figured it out by using the following command for using v0.0.10 
`nextflow pull epi2me-labs/wf-flu -r v0.0.10`
