### ISSUE TITLE
[Bug]: Error executing process > 'pipeline:makeReport (1)'

### ISSUE THREAD

**Issue by llk578496** [epi2me-labs/wf-flu#5]
### What happened?

Hi @mattdmem !

We attempted to use v0.0.10 with the following command:
`nextflow run epi2me-labs/wf-flu -r v0.0.10 --fastq /mnt/data6/FLU/02_fastq/22MB129080.fastq.gz --out_dir /mnt/data6/FLU/04_main/04.1_tmp/22MB129080/wf-flu --align_threads 18 --medaka_consensus_model r941_min_sup_g507`

However, the process terminated with the following error:
> Error executing process > 'pipeline:makeReport (1)'
> 
> Caused by:
>   Process `pipeline:makeReport (1)` terminated with an error exit status (1)
> 
> Command executed:
> 
>   echo '[
>       {
>           "barcode": null,
>           "type": "test_sample",
>           "alias": "22MB129080"
>       }
>   ]' > metadata.json
>       workflow-glue report wf-flu-report.html         --versions versions         --coverage coverage         --typing typing         --processed_type processed_type         --fastqstats fastqstats/per-file-stats.tsv         --nextclade_files nextclade/*         --nextclade_datasets nextclade.csv         --params params.json         --metadata metadata.json
> 
> Command exit status:
>   1
> 
> Command output:
>   (empty)
> 
> Command error:
>   [08:25:34 - workflow_glue] Starting entrypoint.
>   Traceback (most recent call last):
>     File "/home/gilman_siu2/.nextflow/assets/epi2me-labs/wf-flu/bin/workflow-glue", line 7, in <module>
>       cli()
>     File "/home/gilman_siu2/.nextflow/assets/epi2me-labs/wf-flu/bin/workflow_glue/__init__.py", line 62, in cli
>       args.func(args)
>     File "/home/gilman_siu2/.nextflow/assets/epi2me-labs/wf-flu/bin/workflow_glue/report.py", line 110, in main
>       cell.add(span(row[i]))
>     File "/home/epi2melabs/conda/lib/python3.8/site-packages/dominate/tags.py", line 63, in __init__
>       super(html_tag, self).__init__(*args, **kwargs)
>     File "/home/epi2melabs/conda/lib/python3.8/site-packages/dominate/dom_tag.py", line 101, in __init__
>       self.add(*args)
>     File "/home/epi2melabs/conda/lib/python3.8/site-packages/dominate/dom_tag.py", line 209, in add
>       raise ValueError('%r not a tag or string.' % obj)
>   ValueError: None not a tag or string.
> 
> Work dir:
>   /mnt/data6/FLU/work/b0/3c4e6f13c06b73a4c49fe529992999
> 
> Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
> 

This error was not observed when using v0.0.6, but it is occurring with v0.0.10. May we get your advice on this issue?

Thank you very much!

Eddie

### Operating System

Windows 10

### Workflow Execution

EPI2ME Labs desktop application

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

v0.0.10

### Relevant log output

```shell
-
```

**Comment by mattdmem** [comment]
Hi @llk578496,

Thanks for raising this. Looks like an error related to sample sheets and expected values contained within them. We'll look into this and fix in the next version and implement checks for this in our automated testing.

Matt
