### ISSUE TITLE
wf-flu Error executing process > 'pipeline:makeReport'

### ISSUE THREAD

**Issue by andeleconradie** [epi2me-labs/wf-flu#6]
### Operating System

Other Linux (please specify below)

### Other Linux

Ubuntu

### Workflow Version

v1.0.1

### Workflow Execution

EPI2ME Desktop application

### EPI2ME Version

v5.1.9

### Workflow Execution - CLI Execution Profile

None

### What happened?

The pipeline is working until the last step of making the report and then the whole thing fails and there's no usable output.

ERROR ~ Error executing process > 'pipeline:makeReport'
Caused by: Process `pipeline:makeReport` terminated with an error exit status (1)

I have also switched wf-flu revisions to older and newest ones - same problem persists.

### Relevant log output

```shell
-
```

**Comment by andeleconradie** [comment]
[EPI2ME_issue_export.tar.gz](https://github.com/epi2me-labs/wf-flu/files/14140276/EPI2ME_issue_export.tar.gz)

**Comment by cjalder** [comment]
Hi @andeleconradie thanks for sending the issue. A few people have flagged this already (though not on GitHub) - we should be releasing a fix for this in the next release cycle! I'll update here when it's ready

**Comment by cjalder** [comment]
Hi @andeleconradie - we just released v1.1.0 of the workflow, which hopefully has fixed this issue.
Please feel free to open this ticket if the problem persists
