### ISSUE TITLE
Error with Demo Data

### ISSUE THREAD

**Issue by kiranpatil222** [epi2me-labs/wf-flu#7]
### Ask away!

Hi I used the same data and command as given in the demo data, 
`nextflow run epi2me-labs/wf-flu --fastq wf-flu-demo/fastq/ -profile standard`

i got the error as i attached the log
[.nextflow.log](https://github.com/epi2me-labs/wf-flu/files/15059489/default.nextflow.log)

**Comment by mattdmem** [comment]
Hi @kiranpatil222

Sorry for the late reply.

From the nextflow log it looks like you ran out of disk space:

```  docker: failed to register layer: Error processing tar file(exit status 1): write /home/epi2melabs/conda/lib/libstdc++.so.6.0.30: no space left on device.```

Please reply if you need further assistance.

Matt

**Comment by mattdmem** [comment]
closing this due to lack of response - @kiranpatil222 let us know if you have any further issues
